# Generated by Django 3.1.6 on 2021-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='test', max_length=150),
        ),
    ]
